const COLORS = {
  black: '#000000',
  grey_darker: '#272829',
  grey_dark: '#1c1c1e',
  bismark: '#497C8C',
  bismark_dark: '#33545E',
  white: '#ffffff',
  light_grey: '#83878e',
};
const FONT = '"Karla", sans-serif;';

export const theme = {
  colors: COLORS,
  container: {
    backgroundColor: COLORS.black,
    fontFamily: FONT,
    fontWeight: 200,
    color: COLORS.white,
    fontSize: '1rem',
    height: '100vh',
    width: '100vw',
    boxSizing: 'border-box',
  },
  navbarContainer: {
    position: 'fixed',
    top: 0,
    left: 0,
    width: '100%',
    display: 'flex',
    boxSizing: 'border-box',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 2rem',
    backgroundColor: COLORS.grey_dark,
    color: COLORS.bismark,
  },
  navbarLogo: {
    fontSize: '1.5rem',
    fontWeight: 'bold',
  },
  flexContainer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: '1rem',
    boxSizing: 'border-box',
    height: 'auto',
  },
  links: {
    color: COLORS.bismark,
    textDecoration: 'none',
    fontSize: '1.2rem',
    margin: '0 0.5rem',
    transition: 'transform 0.1s ease-in-out',
  },
  footerContainer: {
    position: 'fixed',
    bottom: 0,
    left: 0,
    width: '100%',
    backgroundColor: COLORS.grey_dark,
    padding: '20px',
    boxSizing: 'border-box',
  },
  circularContainer: {
    width: '35px',
    height: '35px',
    borderRadius: '50%',
    border: `1px solid ${COLORS.white}`,
  },
  pageContainer: {
    width: '100vw',
    height: '80vh',
    position: 'fixed',
    top: '9vh',
    left: '0',
    backgroundColor: COLORS.black,
    fontFamily: FONT,
    fontWeight: 200,
    color: COLORS.white,
    fontSize: '1rem',
    boxSizing: 'border-box',
  },
  card: {
    backgroundColor: COLORS.grey_dark,
    color: COLORS.white,
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    width: 'auto',
    maxHeight: '60vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '10px',
    padding: '20px 40px',
    flexDirection: 'column',
  },
  downloadButton: {
    backgroundColor: COLORS.bismark_dark,
    color: COLORS.white,
    padding: '10px 20px',
    borderRadius: '5px',
    border: 'none',
    cursor: 'pointer',
    transition: 'transform 0.1s ease-in-out',
    margin: '15px auto auto',
  },
  textInput: {
    backgroundColor: COLORS.grey_dark,
    color: COLORS.white,
    padding: '10px',
    borderRadius: '5px',
    margin: '10px 0',
    border: `1px solid ${COLORS.bismark_dark}`,
    width: '60vw',
  },
  flexColumn: {
    margin: 'auto 10px',
  },
  styledSelect: {
    padding: '2px 20px',
    border: `1px solid ${COLORS.bismark_dark}`,
    borderRadius: '2px',
    backgroundColor: COLORS.black,
    color: COLORS.light_grey,
    outline: 'none',
    cursor: 'pointer',
    appearance: 'none',
    '-webkit-appearance': 'none',
    '-moz-appearance': 'none',
  },
  styledOption: {
    padding: '2px 20px',
    margin: '0 10px',
    border: `1px solid ${COLORS.bismark_dark}`,
    borderRadius: '2px',
    backgroundColor: COLORS.black,
    color: COLORS.light_grey,
    outline: 'none',
    cursor: 'pointer',
    appearance: 'none',
    '-webkit-appearance': 'none',
    '-moz-appearance': 'none',
  },
  popup: {
    backgroundColor: COLORS.grey_dark,
    padding: '30px',
    position: 'absolute',
    left: "100%",
    borderRadius: '5px',
    zIndex: 1000,
  },
  imageContainer: {
    width: '220px',
    height: 'auto',
  },
};
